#!/usr/bin/env python3
"""Classify hex terrain from DEM elevation + landcover rasters.

Produces:
  data/terrain/hex_terrain.json   — terrain class per hex
  data/terrain/hex_terrain_stats.json — raw stats per hex

Edit tools/terrain/overrides.json to force a hex's class.
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import rasterio
from rasterio.mask import mask
from shapely.geometry import Polygon


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load_hex_grid(path: Path) -> list[dict]:
    data = json.loads(path.read_text())
    return data["hexes"]


def load_overrides(path: Path) -> dict:
    return json.loads(path.read_text()).get("overrides", {})


# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------

def hex_to_polygon(h: dict) -> Polygon:
    coords = [(v["lon"], v["lat"]) for v in h["vertices"]]
    return Polygon(coords)


# ---------------------------------------------------------------------------
# Raster stats
# ---------------------------------------------------------------------------

def _valid_pixels(band: np.ma.MaskedArray, nodata: float | None) -> np.ndarray:
    # band comes from mask(..., filled=False): out-of-polygon pixels are masked,
    # so compressed() drops them instead of counting fill zeros as elevation.
    flat = band.compressed()
    if nodata is not None:
        flat = flat[flat != nodata]
    if flat.size == 0:
        return flat
    flat = flat[np.isfinite(flat.astype(float))]
    return flat


def hex_elevation_stats(poly: Polygon, cache_dir: Path) -> tuple[float, float]:
    dem_dir = cache_dir / "dem"
    if not dem_dir.is_dir():
        raise FileNotFoundError(f"DEM cache directory not found: {dem_dir}")

    pixels: list[float] = []
    for tif in sorted(dem_dir.glob("*.tif")):
        with rasterio.open(tif) as src:
            try:
                out, _ = mask(src, [poly], crop=True, all_touched=False, filled=False)
            except ValueError:
                continue
            nodata = src.nodata
            for band in out:
                v = _valid_pixels(band, nodata)
                pixels.extend(v.tolist())

    if not pixels:
        return 0.0, 0.0

    a = np.array(pixels)
    return float(np.mean(a)), float(np.std(a, ddof=0))


def hex_builtup_frac(poly: Polygon, cache_dir: Path) -> float:
    lc_dir = cache_dir / "landcover"
    if not lc_dir.is_dir():
        raise FileNotFoundError(f"Landcover cache directory not found: {lc_dir}")

    valid = 0
    builtup = 0
    for tif in sorted(lc_dir.glob("*.tif")):
        with rasterio.open(tif) as src:
            try:
                out, _ = mask(src, [poly], crop=True, all_touched=False, filled=False)
            except ValueError:
                continue
            nodata = src.nodata
            for band in out:
                flat = band.compressed()
                if nodata is not None:
                    flat = flat[flat != nodata]
                valid += int(flat.size)
                builtup += int((flat == 50).sum())

    if valid == 0:
        return 0.0
    return builtup / valid


# ---------------------------------------------------------------------------
# Classification
# ---------------------------------------------------------------------------

_VALID_CLASSES = {"mountain", "metropolis", "urban", "hills", "plains"}


def classify_hex(mean_elev_m: float, _elev_std_m: float, builtup_frac: float) -> str:
    if mean_elev_m >= 1000:
        return "mountain"
    if builtup_frac >= 0.50:
        return "metropolis"
    if builtup_frac >= 0.20:
        return "urban"
    if 200 <= mean_elev_m < 1000:
        return "hills"
    return "plains"


def apply_overrides(classes: dict, overrides: dict) -> dict:
    for hid, cls in overrides.items():
        if hid not in classes:
            raise ValueError(f"Unknown hex_id in overrides: {hid!r}")
        if cls not in _VALID_CLASSES:
            raise ValueError(
                f"Invalid override class {cls!r} for hex {hid!r}; "
                f"must be one of {_VALID_CLASSES}"
            )
        classes[hid] = cls
    return classes


# ---------------------------------------------------------------------------
# Sorting
# ---------------------------------------------------------------------------

def sort_key(h: dict) -> tuple[int, int]:
    return h["row"], h["col"]


# ---------------------------------------------------------------------------
# Output writers
# ---------------------------------------------------------------------------

_DESCRIPTION = (
    "Per-hex terrain class for taiwan_hex_grid.json "
    "(generated by tools/terrain/classify_hexes.py; "
    "edit overrides.json, not this file)"
)


def write_hex_terrain(classes: dict, hexes: list[dict], out_dir: Path) -> None:
    sorted_ids = [h["id"] for h in sorted(hexes, key=sort_key)]
    ordered = {hid: classes[hid] for hid in sorted_ids}
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "hex_terrain.json").write_text(
        json.dumps({"description": _DESCRIPTION, "classes": ordered}, indent=2) + "\n"
    )


def write_hex_terrain_stats(stats: dict, hexes: list[dict], out_dir: Path) -> None:
    sorted_ids = [h["id"] for h in sorted(hexes, key=sort_key)]
    ordered = {hid: stats[hid] for hid in sorted_ids}
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "hex_terrain_stats.json").write_text(
        json.dumps(ordered, indent=2) + "\n"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    script_dir = Path(__file__).resolve().parent
    default_repo = str(script_dir.parent.parent)

    parser = argparse.ArgumentParser(description="Classify hex terrain")
    parser.add_argument(
        "--cache-dir",
        default=str(Path.home() / "geodata" / "hexcombat"),
        help="Raster cache directory (default: ~/geodata/hexcombat)",
    )
    parser.add_argument(
        "--repo-root",
        default=default_repo,
        help="Repository root (default: two dirs up from script)",
    )
    args = parser.parse_args()

    cache_dir = Path(args.cache_dir)
    repo_root = Path(args.repo_root)
    grid_path = repo_root / "data" / "taiwan_hex_grid.json"
    out_dir = repo_root / "data" / "terrain"
    overrides_path = script_dir / "overrides.json"

    if not grid_path.is_file():
        print(f"ERROR: Hex grid not found: {grid_path}", file=sys.stderr)
        sys.exit(1)

    hexes = load_hex_grid(grid_path)
    n = len(hexes)
    print(f"Loaded {n} hexes from {grid_path}")

    # Build polygons once
    polys = {h["id"]: hex_to_polygon(h) for h in hexes}

    classes: dict[str, str] = {}
    stats: dict[str, dict] = {}

    for i, h in enumerate(hexes):
        hid = h["id"]
        mean_elev, elev_std = hex_elevation_stats(polys[hid], cache_dir)
        builtup = hex_builtup_frac(polys[hid], cache_dir)

        stats[hid] = {
            "mean_elev_m": round(mean_elev, 1),
            "elev_std_m": round(elev_std, 1),
            "builtup_frac": round(builtup, 3),
        }
        classes[hid] = classify_hex(mean_elev, elev_std, builtup)

    # Apply manual overrides
    if overrides_path.is_file():
        overrides = load_overrides(overrides_path)
        if overrides:
            print(f"Applying {len(overrides)} override(s) from {overrides_path}")
            classes = apply_overrides(classes, overrides)

    # Write outputs
    write_hex_terrain(classes, hexes, out_dir)
    write_hex_terrain_stats(stats, hexes, out_dir)
    print(f"Wrote {out_dir / 'hex_terrain.json'}")
    print(f"Wrote {out_dir / 'hex_terrain_stats.json'}")

    # Print summary
    counts: dict[str, int] = {}
    for c in classes.values():
        counts[c] = counts.get(c, 0) + 1
    print(f"\nClass counts ({sum(counts.values())} hexes):")
    for c in sorted(counts):
        print(f"  {c}: {counts[c]}")


if __name__ == "__main__":
    main()
