extends Node
class_name EventBusType

signal hex_selected(hex_id: String)
signal brigade_selected(brigade_id: String)
signal selection_cleared()
signal turn_resolved(turn_number: int)
signal combat_resolved(summaries: Array)
signal phase_changed(phase: int)
signal reachable_hexes_changed(hex_ids: Array)
signal move_mode_changed(mode: String)
signal move_order_issued(brigade_id: String, target_hex: String, mode: String)
signal turn_advanced(turn_number: int)
signal commit_options_changed(target_hex: String, options: Array)
signal brigade_committed(brigade_id: String, target_hex: String)
signal offload_resolved(manifest: Dictionary)
signal supply_updated(summary: Dictionary)
signal ijfs_resolved(summary: Dictionary)
signal antiship_resolved(summary: Dictionary)
signal frontline_resolved(summary: Dictionary)
